const splashes = [
    "\"bababooey\"",
    "as seen on tv!",
    "trans rights!",
    "trans rights!",
    "trans rights!",
    "trans rights!",
    "trans rights!",
    "trans rights!",
    "trans rights!",
    "trans rights!",
    "trans rights!",
    "trans rights!",
    "gay rights!",
    "gay rights!",
    "gay rights!",
    "2% reduced fat",
    "\"doot doot\"",
    "obey the funk!",
    "`${splashText}`",
    "o kama sona e toki pona!",
    "kijetesantakalu li suwi",
    "Ph'nglui mglw'nafh Cthulhu R'lyeh wgah'nagl fhtagn",
    "\"sexier than it first appears\"",
    "now in color!",
    "\"everybody do the flop!\"",
    "#1 New York Times bestseller (trust me bro)",
    "being gay, <s>doing crime</s> since 2003",
    "y He require ur is r",
    "Technoblade never dies!",
    "also try Minecraft!",
    "gender? I barely know her!",
    "gender? whats that?",
    "click for details",
    "supercalifragilisticexpialidocious",
    "for a limited time only!",
    "Who let the frogs out?",
    "uwu",
    "wow",
    "woAh",
    "\"lord of the gays\"",
    "\"yabadabadoooooo\"",
    "trapezoids banned on grounds of sex appeal",
    "a",
    "oh no, not again",
    "don't panic"
]

document.getElementById('splash').innerHTML = splashes[Math.floor(Math.random()*splashes.length)]
